<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<AssemblyName>MessageBus.Hosts.Orders</AssemblyName>
		<RootNamespace>MessageBus.Hosts.Orders</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\MessageBus.Explorer\MessageBus.Explorer.csproj" />
		<ProjectReference Include="..\..\MessageBus.Operations.Client\MessageBus.Operations.Client.csproj" />
		<ProjectReference Include="..\..\MessageBus.OpenTelemetry\MessageBus.OpenTelemetry.csproj" />
		<ProjectReference Include="..\..\MessageBus.Persistence.EntityFrameworkCore\MessageBus.Persistence.EntityFrameworkCore.csproj" />
		<ProjectReference Include="..\..\MessageBus.Transport.AzureServiceBus\MessageBus.Transport.AzureServiceBus.csproj" />
		<ProjectReference Include="..\..\MessageBus.Transport.RabbitMq\MessageBus.Transport.RabbitMq.csproj" />
		<ProjectReference Include="..\Hosts.Infrastructure\Hosts.Infrastructure.csproj" />
		<ProjectReference Include="..\Hosts.Orders.Contracts\Hosts.Orders.Contracts.csproj" />
		<ProjectReference Include="..\Hosts.ServiceDefaults\Hosts.ServiceDefaults.csproj" />
	</ItemGroup>
</Project>
