<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>MessageBus.Persistence.EntityFrameworkCore</AssemblyName>
		<RootNamespace>MessageBus.Persistence.EntityFrameworkCore</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MessageBus.Core\MessageBus.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="MessageBus.Persistence.EntityFrameworkCore.Tests" />
	</ItemGroup>
</Project>
