<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>MessageBus.OpenTelemetry</AssemblyName>
		<RootNamespace>MessageBus.OpenTelemetry</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="OpenTelemetry.Api" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MessageBus.Core\MessageBus.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="MessageBus.OpenTelemetry.Tests" />
	</ItemGroup>
</Project>
