<Project Sdk="Microsoft.NET.Sdk">
	<Sdk Name="Aspire.AppHost.Sdk" Version="13.5.3" />
	<PropertyGroup>
		<AssemblyName>MessageBus.Hosts.Aspire</AssemblyName>
		<RootNamespace>MessageBus.Hosts.Aspire</RootNamespace>
	</PropertyGroup>


	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<IsAspireHost>true</IsAspireHost>
		<UserSecretsId>messagebus-hosts-aspire</UserSecretsId>
		<NoWarn>$(NoWarn);ASPIRE010</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.AppHost" />
		<PackageReference Include="Aspire.Hosting.Azure.ServiceBus" />
		<PackageReference Include="Aspire.Hosting.RabbitMQ" />
		<PackageReference Include="Aspire.Hosting.Seq" />
		<PackageReference Include="Aspire.Hosting.SqlServer" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="rabbitmq\**" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\MessageBus.Operations.Web\MessageBus.Operations.Web.csproj" />
		<ProjectReference Include="..\Hosts.Billing\Hosts.Billing.csproj" />
		<ProjectReference Include="..\Hosts.Infrastructure\Hosts.Infrastructure.csproj" IsAspireProjectResource="false" />
		<ProjectReference Include="..\Hosts.Orders\Hosts.Orders.csproj" />
	</ItemGroup>
</Project>
